var:
  last_build_time: 1523265194
  option:
    ascii_punct: false
    full_shape: false
    simplification: true
  previously_selected_schema: luna_pinyin
  schema_access_time:
    luna_pinyin: 1523259487
    luna_pinyin_simp: 1514880509